### ISSUE TITLE
How to auto clear margins on nested cols

### ISSUE THREAD

**Issue by himedlooff** [cfpb/cf-grid#1]
Currently there is no way to auto clear left and right margins on nested columns so that they align with other columns that are not nested.

The example page achieves this with a [custom wrapper and custom less](https://github.com/cfpb/cf-grid/blob/gh-pages/src/examples/grid/static/example.less#L47-L49) but it should come standard with ghost.

I think this means recommending that all columns get wrapped in a wrapper and that nested wrappers have a left and right margin of 0.

@contolini @Scotchester what do you think?

---

@Scotchester commented 14 days ago  

> I still love that the top level doesn't have to have a wrapper. What if we just required a wrapper when you want to nest?

@himedlooff commented 14 days ago  

> I'm ok with that too, like a .nested-cols class or something.

**Comment by ascott1** [comment]
I'm a big fan of using a `.group` class as a container for floats. I believe I first came across the idea in Handcrafted CSS in place of `.clearfix.`

**Comment by himedlooff** [comment]
Yeah maybe `.column-group` or `.col-group`?

**Comment by ascott1** [comment]
I like `.col-group`, it's short and descriptive.

**Comment by Scotchester** [comment]
I think there might be a small misunderstanding here. Ghost does not use floats. I think the "auto clear" language in this issue might have implied the wrong thing. What @himedlooff is actually referring to is aligning the left and right margins of a nested grid with the parent grid. @ascott1 Ping me on IM if you want to screen-share and discuss together.

**Comment by ascott1** [comment]
Gotcha... should probably avoid Github issues "late" at night. That said, I'm already encountering the issue described above. I'll ping you later to discuss.

**Comment by himedlooff** [comment]
Floats or no floats we still need a wrapper to pull the margins out.

**Comment by ascott1** [comment]
Closing this as it was resolved with the .nested-col-group() mixin
