### ISSUE TITLE
0.7.0 release being ignored by Bower?

### ISSUE THREAD

**Issue by ascott1** [cfpb/cf-grid#13]
For some reason when updating bower dependencies using the `grunt vendor` task cf-grid was being ignored. Pinning it to the 0.6.8 release seemed to work find.

**Comment by ascott1** [comment]
Yeah, this is putting the hurt on me right now as the 0.6.8 release doesn't include `.nested-col-group`

**Comment by ascott1** [comment]
Pinned down the issue to this commit: https://github.com/cfpb/cf-grid/commit/c6f1837b4726eb1f5347ee5034932a6efa51ced2

**Comment by Scotchester** [comment]
Fixed with #14.

**Comment by ascott1** [comment]
#14 did not solve the issue.

**Comment by ascott1** [comment]
Bah, it was because of this in my project's Bower.json:

``` json
  "exportsOverride": {
    "cf-grid": {
      "less": "src/ghost.less"
    },
```
