### ISSUE TITLE
Deprecate box-sizing-polyfill

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cf-grid#25]
Pending the outcome of https://github.com/cfpb/front-end/issues/31 and if it excludes IE6 and IE7, cf-grid should drop support for IE6 & IE7 and remove the [box-sizing-polyfill](https://github.com/Schepp/box-sizing-polyfill). Since this polyfill isn't included in the JS bundle like other polyfills it presents unnecessary burden for implementators of cf-grid, which may not be otherwise supporting IE6/7 anyway. 

Alternatively, provide a means to exclude the box-sizing-polyfill and still use cf-grid if a project wants to use the grid but doesn't care about IE6/7 support.

**Comment by anselmbradford** [comment]
box-sizing-polyfill is imported in https://github.com/cfpb/cf-grid/blob/gh-pages/bower.json#L25

**Comment by himedlooff** [comment]
There are also a bunch of `.lt-ie8` rules you could ditch as well if you do this.
