### ISSUE TITLE
Split demo into legacy.html and semantic.html?

### ISSUE THREAD

**Issue by himedlooff** [cfpb/cf-grid#7]
The current demo demonstrates using both the base Less file and the legacy Less file. I think we should split this up so that there are two demos.

**Demo 1** should be similar to what we have now where it shows all the grid combinations except it should use the generated legacy CSS file instead of the legacy Less file. This would be a better demo for someone who is interested in using the legacy version.

**Demo 2** should use an example Less file that demonstrates using `cf-grid.less` the semantic way where you define your own columns. This would be a better demo for someone who is interested in using this in the semantic fashion.

**Comment by KimberlyMunoz** [comment]
Closing in favor of new discussion on new documentation.
